### ISSUE TITLE
Deleting and Editing Posts

### ISSUE THREAD

**Issue by Stringfelloh** [snazy2000/Ninjah-Gaming#10]
So, this is an issue which may not be main priority, but would sure be quite useful.
Users are unable to delete or edit posts, so once it's there, it can't be removed.

**Comment by Sladewill** [comment]
Users will never be able to delete their own posts only administrators can do this.

Also why cant you edit?

**Comment by snazy2000** [comment]
Edit issue fixed when update next pushed to live server :)
