### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Marcuzz** [snazy2000/Ninjah-Gaming#15]
http://www.ninjah-gaming.co.uk/profile/Marcuz/

Image is off and buttons are not centered (I know you probably already know but this is a reminder)

**Comment by ghost** [comment]
profile images dont seem to have a limit

http://www.ninjah-gaming.co.uk/profile/Jelhi/

**Comment by Sladewill** [comment]
Fixed dev deploying soon.
