### ISSUE TITLE
Switch from mobile version

### ISSUE THREAD

**Issue by Newjorciks** [snazy2000/Ninjah-Gaming#17]
It would be very useful if there would be a button at the bottom of mobile version to switch to desktop version, so some phones (Like my one XD ) for which the mobile version is unusuable, i could atleast use desktop version.

**Comment by snazy2000** [comment]
This is not possible the site is responsive and will change the style of website depending on the size of screen auto maticly if u make your website on pc same size as a phone y he site will change we wi'll fix mobile issues at some point they are not priority.
