### ISSUE TITLE
infinite load and memory leak involving rocket from cloudflare

### ISSUE THREAD

**Issue by ghost** [snazy2000/Ninjah-Gaming#18]
there is a issue with rocket.js 
it is causing infinite loading of the Home URL "http://ninjah-gaming.co.uk/home/"
it seems to be stuck on a function from within rocket, although errors seem to be surpressed 
it is repeating the same function call over and over again,
see attached screenshot of function call volume
memory useage for firefox when only that url is open (infinite loading) creeps up to 50MB currently, although not a massive issue its still a leak...

i went to get a screenshot of the profiler, memory peaked to 100MB + caused a crash 

here is a screenshot of the crash, could not get a screenshot of the profiler due to this happening :S
![woops](https://f.cloud.github.com/assets/7030010/2490391/e91e1d8e-b1a6-11e3-9a83-988655e3eef1.png)

**Comment by snazy2000** [comment]
This is a cloudflare issue I will get in touch and see if they can help out

**Comment by ghost** [comment]
yup, they do say that rocket.js can cause some issues, although not 100% what the issue is as its being called from an anonymous function(s)

**Comment by Sladewill** [comment]
![tracert](https://f.cloud.github.com/assets/6969435/2491452/3837e5f8-b1ed-11e3-9a6c-72457924732a.png)

**Comment by Sladewill** [comment]
We are currently in talks with cloudflare about this issue, they just want to get some more information from anyone thats getting the issue, can we get a tracert from anyone and a har dump if possible.

**Comment by Marcuzz** [comment]
![2014-03-22_2319](https://f.cloud.github.com/assets/3168421/2492068/151c6224-b210-11e3-85b8-83647c2710fc.png)
![2014-03-22_2320](https://f.cloud.github.com/assets/3168421/2492070/432167e6-b210-11e3-8ccb-8ed58155405e.png)

tracert's from two different locations.

har dump from local: http://marcuz.co.uk/files/www.ninjah-gaming.co.uk.rar

**Comment by Sladewill** [comment]
Rocket.js is currently disabled, lazyload images is still on and the issue seems to only relate to that so it seems stable for the time being we still need to get back in contact with cloudflare to see if we can assit with getting this resolved as its quite annoying.
