### ISSUE TITLE
Editing Account Info Page

### ISSUE THREAD

**Issue by Dubnubs** [snazy2000/Ninjah-Gaming#2]
Upon editing something on the account info page this ( http://puu.sh/7yk9n.png)  error will pop up at the top of the page, it then proceeds to delete everything saved on the page and set it to default, however it will not save it after deleting everything so if you reload the page everything will be back to as if you never edited it in the first place.

TL;DR....... 
Before: http://puu.sh/7ykvO.png 
After submitting the changes : http://puu.sh/7ykyr.png
then after leaving the page and returning it would return to : http://puu.sh/7ykvO.png

**Comment by snazy2000** [comment]
Thanks for the bug report we will look in to this soon as we can :)

**Comment by NinjahMudkip** [comment]
Don't know if this helps, but the error is as posted-

Warning: checkdate() expects parameter 3 to be long, string given in /var/www/database.php on line 379

With the number of the line being variable.
