### ISSUE TITLE
Ban list for servers

### ISSUE THREAD

**Issue by ghost** [snazy2000/Ninjah-Gaming#24]
![capture](https://f.cloud.github.com/assets/7038460/2493385/3f33c192-b292-11e3-9805-c875dc128569.PNG)

Could we fix this?, it would be nice to see the bans and such so I can sort out people asking me about who banned them and why/how long.

**Comment by Sladewill** [comment]
First off you shouldn't have been on there its not yet finished so don't try and access areas of the site not yet available.
