### ISSUE TITLE
Editing/deleting posts?

### ISSUE THREAD

**Issue by Marshal-Lee** [snazy2000/Ninjah-Gaming#25]
When you try to edit a post, after you type in the edit and click edit at the bottom, it simply refreshes the page at which you are currently on, if you click back the post doesnt get edited, meaning you have to post again if you wanted to explain or change something in the prior post. Also if you accidentally doublepost, there is no delete button. I have encountered both of these problems and due to it i have been forced to post 3 times in a row explaining why i had to post 3 times in a row.

**Comment by Sladewill** [comment]
Users are specifically not allowed to delete posts due to security issues and general moderator is done by full-mods+.

As for editing your post you should be able to easily edit, are you sure there are no errors?

**Comment by RandyMan25** [comment]
You actually can't edit the posts Slade. I tried just now and it takes me straight back to the edditing page with my eddited stuff

**Comment by Sladewill** [comment]
http://www.ninjah-gaming.co.uk/forum/Old_Applications_-_Reports_-_Appeals/test_topic_24-03-2014/

With the use of a test account editing does work. When was the last time you actually tried to and was the post locked. If the post is locked you will not be able to edit anything.

**Comment by Marshal-Lee** [comment]
I tried to edit my post on marxblues event around 8 pm due to my accidental double post, and as far as I know the post wasn't locked so I'm not sure if its just an occasional bug or what.

**Comment by RandyMan25** [comment]
i just tried just now to edit one o my posts and it didn't work. I tried editing it on the Civ 5 post but wouldn't let me edit. 07:25 GMT 00:00 London 24/03/2014

**Comment by Marshal-Lee** [comment]
I have a theory, was the account you used to test it made before the website was updated or what, cause if it was made after it may be a bug with the accounts made beforehand?

**Comment by Sladewill** [comment]
The account has been on the system since it first started, the account is the second one in the system apart from mine

**Comment by Sladewill** [comment]
I've tried numerous times with different accounts can one of you message me on steam and I have a look over teamviewer?

**Comment by Marshal-Lee** [comment]
Sure, but i have no idea what teamviewer is XD

**Comment by RandyMan25** [comment]
i'll do it m8 got it ready.

**Comment by Sladewill** [comment]
Right its fixed now thanks to ranndy for helping me :D
