### ISSUE TITLE
Verification?

### ISSUE THREAD

**Issue by RandyMan25** [snazy2000/Ninjah-Gaming#26]
When I try to log in my account on my phone it asks for it I be verified and to go to my email. Should it really be doing this?

**Comment by snazy2000** [comment]
If the login works on pc then I don't know what your doing as it's the same web page for both no code is different

**Comment by RandyMan25** [comment]
keeps saying "You haven't yet activated your account. please check your email for instructions!" even though i have looked at my mail and there is nothing there.

**Comment by snazy2000** [comment]
You need to go to the resend page and send your verification email again

**Comment by RandyMan25** [comment]
Yeh cheers that works :)
