### ISSUE TITLE
Ninjah-BaseWars

### ISSUE THREAD

**Issue by Flashpyy** [snazy2000/Ninjah-Gaming#28]
Hey I'm Joey.238 (ING)
The Server Is like lagging all the time it's a Awesome server but the lagg is so hard.
Can u plz do something about this is like to play whitout lag. Like can u buy a host plz
Ill realy apricaet that
Sorry for my bad english
Greetings Joey

**Comment by Sladewill** [comment]
This git is only for the website please post on the forums

**Comment by Flashpyy** [comment]
It says i blocked on website :/

**Comment by Sladewill** [comment]
Still not going to deal with it, doing website development nothing to do with basewars.
