### ISSUE TITLE
BB Codes

### ISSUE THREAD

**Issue by Marcuzz** [snazy2000/Ninjah-Gaming#29]
The BB Code bar does not work when editing a post. This does not apply when you create a new one.

**Comment by snazy2000** [comment]
Ah yeah forgot to add name tag will fix later

**Comment by Sladewill** [comment]
Snazy did you actually fix this if so please close this issue.

**Comment by snazy2000** [comment]
No haven't had time

**Comment by snazy2000** [comment]
Fixed on dev
