### ISSUE TITLE
"You are here" line wrong

### ISSUE THREAD

**Issue by Marcuzz** [snazy2000/Ninjah-Gaming#30]
http://gyazo.com/9e68a1bdda93714dc66093bdc6a563ce
Martin sent me that.

It's grabbing the actual category name not the subforum. Important should be Information

**Comment by snazy2000** [comment]
Also bug with the new in queries were if there is not any posts not read it errors

**Comment by Sladewill** [comment]
I think I've manged to fix that error on the dev site, will be deployed soon most likely tomorrow when I can deploy some other changes as well.
