### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by JackReacher1** [snazy2000/Ninjah-Gaming#32]
I know Glothox had the same issue as me (http://puu.sh/7PkkW), but when I go to my email to activate my account, I can't click the link. http://puu.sh/7Pkmf

**Comment by Sladewill** [comment]
We need more information than that, what link were you given if you copy and paste that here we can debug why its happening.

**Comment by JackReacher1** [comment]
No worries, It's clickable now, for some reason I couldn't click the link earlier :S
