### ISSUE TITLE
Unable to reply

### ISSUE THREAD

**Issue by Marshal-Lee** [snazy2000/Ninjah-Gaming#34]
I have tried on multiple threads but everytime i try to reply to a post i get this error: 
Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /var/www/database.php on line 123
array(1) { [0]=> array(3) { [0]=> string(5) "23000" [1]=> int(1052) [2]=> string(38) "Column 'ID' in field list is ambiguous" } }

**Comment by RandyMan25** [comment]
Duplicate #33. You do post it just shows an error saying it didn't

**Comment by snazy2000** [comment]
May be a subscription issue I'm sure sladewill will look in to it soon

**Comment by Marshal-Lee** [comment]
Randy,  are you sure that i am actually posting, because i checked the threads i posted on and i still cant see my post e.g. marxblues cs:go post

**Comment by RandyMan25** [comment]
hmm i don't know but when i got this it said that an error popped up and then i went back to the post and it said i posted.

**Comment by Sladewill** [comment]
Errors gone, the issue behind it is still there though closing the issue I'm aware of this and its something unrelated.
