### ISSUE TITLE
Reset password doesn't actually seem to reset it

### ISSUE THREAD

**Issue by BenWoodford** [snazy2000/Ninjah-Gaming#41]
Couldn't login (Cuebosh) once I registered (not sure if this was an error on my part or the system's), tried to reset my password and it still wouldn't take.

Oh, also if you don't put an email in the email field of password reset it'll throw an error on the Mailer, rather than incurring a validation error.

**Comment by Sladewill** [comment]
Fixed on the development version, we will be pushing tomorrow with a few fixes and changes.
